# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: API Test Automation

permissions:
  contents: read
  checks: write
  pull-requests: write
  issues: write

# on:
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]
#   schedule:
#     - cron: '30 7 * * *' #crone job schedule at 1.00PM IST

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

      #update the java versions
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

      #place to configure maven build
    - name: Build with Maven
      run: mvn clean test -Dsuite=regression

      #configure to store the log file, using 'Upload a Build Artifact' in marketplace
    - name: Upload a Build Artifact
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
        # Artifact name
        name: Logs #artifact name
        # A file, directory or wildcard pattern that describes what to upload
        path: logs/

    #configure the test report by default we able to integrate junit repot only
    - name: Publish Test Report
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: TestNG Result
        path: target/surefire-reports/junitreports/TEST-*.xml 
        reporter: java-junit

    - name: Upload Extent Report
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
        name: Extent-Report
        path: test-output/reports/
     
